daysUntilStale: 84
daysUntilClose: 14
exemptLabels:
  - enhancement
  - technical debt
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be _closed in two weeks_ if no further activity occurs.
  :heart: Thank you for your contributions to [z85-cli](https://www.npmjs.com/package/z85-cli)!
closeComment: false