language: node_js
node_js:
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8
  - 6
addons:
  code_climate:
    repo_token:
      secure: CH0YLY3FhLz9J+6ZmCwan3wCiUMJk3oE9dAqZtloSg1h7gmWJL1RZPyispI0fJ0W6oumTARAw3nHaU6E8hSirf7/mDbGCZjzw3LTQW0v0RyPGVtgYjirGhD2ZlaUpidzFqJMaSSwStoP3+TQSEwuhqDBdPVM544ZyIice+zXTg8=
before_script:
  - npm install -g grunt-cli
after_script:
  - npm run coveralls
  - npm run codeclimate
sudo: false
deploy:
  provider: npm
  email: npmjs.org@kimminich.de
  api_key:
    secure: GdG3IqhIoDCeyQ1iBMFu8U6dYzsXS2cej0Jj8aF6y48jjmNlt8zl8VyAtSHLGCRWMthPJvWOVbavmqonDrr1kG2bxZv4h5LMgsHscGDr1osizOgsV96KRgHkM5W7JrcG/GUSAKSAJAdariqps27eiVZkweAnX/F/p6oqzIAr/VM=
  on:
    tags: true
    repo: bkimminich/z85-cli
    node: 10
